### ISSUE TITLE
Rest connections not terminating

### ISSUE THREAD

**Issue by klaypigeon** [jantman/nagios-scripts#3]
I do not believe this is actually an issue with the script, but thought you might have some insight that would help me and others. It does not appear that the API connections are terminating in a reasonable time limit. My active connections count is up to 1100 after running the check for 24 hours. (Operations>Master Status>Connections).

**Comment by jantman** [comment]
@klaypigeon I have no idea which of these scripts you're talking about, but I haven't used any of these (or Nagios) in many, many years...

**Comment by klaypigeon** [comment]
Lol, well I was talking about the Tidal rest script to check connection
state. Been there though. I have all these Tivoli scripts I haven't used
for years now.
